version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.2
    - 6.3.0
    - 6.3.1
  - dependency-name: watchify
    versions:
    - 4.0.0
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.1
    - 7.0.3
