version: 2.1
orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers
    environment:
      TZ: "America/Chicago"
    working_directory: ~/dateline
    steps:
      - checkout
      - restore_cache:
          key: npm-cache{{ checksum "package.json" }}
      - run: npm ci
      - save_cache:
          key: npm-cache{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm test
