// Generated by CoffeeScript 1.8.0
(function() {
  var Deadline, formatHours, formatMinutes, monthNames, topOfHour;

  Deadline = function(dateObj) {
    if (dateObj == null) {
      dateObj = new Date();
    }
    dateObj.getAPTime = function(options) {
      var hour, hours, minute, minutes, timeOfDay;
      if (options == null) {
        options = {};
      }
      hours = dateObj.getHours();
      minutes = dateObj.getMinutes();
      if (hours === 0 && minutes === 0) {
        return 'midnight';
      }
      if (hours === 12 && minutes === 0) {
        return 'noon';
      }
      timeOfDay = hours < 12 ? 'a.m.' : 'p.m.';
      hour = formatHours(hours);
      if (topOfHour(minutes) && (options.includeMinutes == null)) {
        return "" + hour + " " + timeOfDay;
      }
      minute = formatMinutes(minutes);
      return "" + hour + ":" + minute + " " + timeOfDay;
    };
    dateObj.getAPDate = function(options) {
      var date, month, monthName, year;
      if (options == null) {
        options = {};
      }
      month = dateObj.getMonth();
      date = dateObj.getDate();
      year = dateObj.getFullYear();
      monthName = monthNames[month];
      if ((year === new Date().getFullYear()) && (options.includeYear == null)) {
        return "" + monthName + " " + date;
      }
      return "" + monthName + " " + date + ", " + year;
    };
    return dateObj;
  };

  module.exports = Deadline;

  formatHours = function(hours) {
    if (hours === 0) {
      return 12;
    }
    if (hours > 12) {
      return hours - 12;
    }
    return hours;
  };

  topOfHour = function(minutes) {
    return minutes === 0;
  };

  formatMinutes = function(minutes) {
    if (minutes < 10) {
      return "0" + minutes;
    }
    return minutes;
  };

  monthNames = ['Jan.', 'Feb.', 'March', 'April', 'May', 'June', 'July', 'Aug.', 'Sept.', 'Oct.', 'Nov.', 'Dec.'];

}).call(this);
